POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
  "title": "my first blog",
  "author": "Kirankumar Sripati",
  "url": "https://example.com/blog/1",
  "likes": 10,
  "user": "5d87a78dd8acbe116b28261a"
}